const Joi = require('joi');

const createProductSchema = Joi.object({
  category_id: Joi.number().integer().positive().allow(null),
  name: Joi.string().min(1).max(200).required(),
  sku: Joi.string().max(50).allow('', null),
  barcode: Joi.string().max(100).allow('', null),
  barcode_type: Joi.string().valid('ean13', 'ean8', 'upca', 'upce', 'code128', 'code39', 'qrcode').default('code128'),
  description: Joi.string().allow('', null),
  purchase_price: Joi.number().min(0).precision(2).default(0),
  selling_price: Joi.number().min(0).precision(2).default(0),
  wholesale_price: Joi.number().min(0).precision(2).allow(null),
  discount_price: Joi.number().min(0).precision(2).allow(null),
  stock_quantity: Joi.number().min(-999999).precision(3).default(0),
  low_stock_threshold: Joi.number().min(0).precision(3).default(10),
  unit: Joi.string().max(20).default('pcs'),
  tax_percentage: Joi.number().min(0).max(100).precision(2).default(0),
  is_active: Joi.boolean().default(true),
  is_featured: Joi.boolean().default(false),
  track_stock: Joi.boolean().default(true),
  type: Joi.string().valid('good', 'service').default('good'),
  expiry_date: Joi.date().allow(null),
  manufacturer: Joi.string().max(200).allow('', null),
  batch_number: Joi.string().max(50).allow('', null),
  requires_prescription: Joi.boolean().default(false),
  images: Joi.array().items(Joi.string()).default([]),
});

const updateProductSchema = Joi.object({
  category_id: Joi.number().integer().positive().allow(null),
  name: Joi.string().min(1).max(200),
  sku: Joi.string().max(50).allow('', null),
  barcode: Joi.string().max(100).allow('', null),
  barcode_type: Joi.string().valid('ean13', 'ean8', 'upca', 'upce', 'code128', 'code39', 'qrcode'),
  description: Joi.string().allow('', null),
  purchase_price: Joi.number().min(0).precision(2),
  selling_price: Joi.number().min(0).precision(2),
  wholesale_price: Joi.number().min(0).precision(2).allow(null),
  discount_price: Joi.number().min(0).precision(2).allow(null),
  stock_quantity: Joi.number().min(-999999).precision(3),
  low_stock_threshold: Joi.number().min(0).precision(3),
  unit: Joi.string().max(20),
  tax_percentage: Joi.number().min(0).max(100).precision(2),
  is_active: Joi.boolean(),
  is_featured: Joi.boolean(),
  track_stock: Joi.boolean(),
  type: Joi.string().valid('good', 'service'),
  expiry_date: Joi.date().allow(null),
  manufacturer: Joi.string().max(200).allow('', null),
  batch_number: Joi.string().max(50).allow('', null),
  requires_prescription: Joi.boolean(),
  images: Joi.array().items(Joi.string()),
}).min(1);

module.exports = { createProductSchema, updateProductSchema };
